Add --tarball option to build for a quick check of packaging.
git-svn-id: http://scm.sipfoundry.org/rep/sipX/main@4903 a612230a-c5fa-0310-af8b-88eea846685b

diff --git a/build b/build
--- a/build
+++ b/build
@@ -158,6 +158,46 @@ incrementalBuild()
     fi
 }
 
+## T A R B A L L S
+tarBuild()
+{
+    Project=$1
+    ## echo to stderr to help decipher warnings and errors between projects
+    echo "Starting tarball build of $Project" >&2
+
+    Success=false
+    echo "Building $Project tarball"
+    pushd $Project || return 1
+
+    setConfigureSwitches 
+
+    if autoreconf --force --install
+    then
+        mkbuilddir build
+        cd build
+        if ../configure $ConfigureSwitches --prefix $Destination
+        then
+            if make -s dist
+            then
+                Success=true
+            fi
+        fi
+    fi
+    popd
+
+    if test "$Success" = "true"
+    then
+        echo "SUCCESS : $Project tarball built successfully"
+        echo ""
+        return 0
+    else
+        builderr "ERROR : $Project tarball failed to build!!!"
+        BuildReturn=-1
+        echo ""
+        return 1
+    fi
+}
+
 ## D I S T R I B U T I O N
 distributionBuild()
 {
@@ -422,6 +462,10 @@ do
         Action=DISTRIBUTION
         ;;
 
+        -t|--tarball)
+        Action=TARBALL
+        ;;
+
         -r|--rpm)
         Action=RPM
         ;;
@@ -527,6 +571,28 @@ then
             cleanBuild $Project
             incrementalBuild $Project
         fi
+      else
+          echo "$Project missing (skipped) " 1>&2
+          echo "$Project missing (skipped) " >> build.err
+      fi
+    done
+
+    cat build.err
+    exit $BuildReturn
+elif test "$Action" = "TARBALL" 
+then
+    if test -z "$Destination"
+    then
+        echo "Must specify <destination>" 1>&2
+        exit 1
+    fi
+
+    mkbuilddir $Destination
+
+    for Project in `ProjectsInOrder $Projects`; do
+      if [ -d $Project ]
+      then
+        tarBuild $Project
       else
           echo "$Project missing (skipped) " 1>&2
           echo "$Project missing (skipped) " >> build.err
@@ -649,23 +715,32 @@ Options are:
                        is only considered a failure if this second attempt
                        fails (see --failfast).
 
-     --distribution    Calls 'make dist' to builds tarballs. Destination
-                       directory is required but no files are installed or
-                       modified in that directory.
+     --distribution|-d Calls 'make dist' to builds tarballs and then builds 
+                       from those tarballs. 
+                       Destination directory is required for configuration 
+                       purposes, but no files are installed or modified in that
+                       directory.
 
-     --clean           Deletes all output and generated files including
+     --tarball|-t      Calls 'make dist' to build tarballs, but does not build 
+                       from them (useful to check whether or not packaging 
+                       works but much quicker than --distribution).. 
+                       Destination directory is required for configuration 
+                       purposes, but no files are installed or modified in that
+                       directory.
+
+     --clean|-c        Deletes all output and generated files including
                        files generated by autoconf and automake.  
                        If the --projects option is used to explictly specify
                        a list of projects, then this implies --no-deps.
                        This does *not* delete any installed files.
 
-     --sudo            Sudo when installing packages
+     --sudo|-s         Sudo when installing packages
 
-     --failfast        Stop after first build error, leaving any remaining projects
+     --failfast|-f     Stop after first build error, leaving any remaining projects
                        unbuilt.  In an incremental build, this also disables the
                        automatic clean and retry.
 
-     --projects        Space or comman delimited list of projects to operate on;
+     --projects|-p     Space or comman delimited list of projects to operate on;
                        this option may be specified multiple times.
                        Example: --projects "sipXpbx sipXphone".
                             or  --projects sipXpbx,sipXphone
@@ -677,25 +752,25 @@ Options are:
                        specifying 'sipXtackLib' would automatically
                        also build 'sipXportLib' (to disable, use --no-deps).
 
-     --no-deps         Build exactly the specified targets; do not build the 
+     --no-deps|-nd     Build exactly the specified targets; do not build the 
                        projects they depend on.
 
-     --no-check        Does not run unit tests. 
+     --no-check|-nc    Does not run unit tests. 
                        WARNING: If Douglas finds out you didn't run unit tests 
                        before you checked your code in, he's going to put tacks 
                        on your chair.
 
-     --exec            Execute remaining portion of commandline after changing the
+     --exec|-x         Execute remaining portion of commandline after changing the
                        current directory into the project's root directory. 
                        Examples:
                            build -x pwd | xargs grep -rl SomeString
                            build -x svn status
 
-     --rpm             Build and install RPMs.
+     --rpm|-r          Build and install RPMs.
 
-     --rpmclean        Remove RPMs
+     --rpmclean|-rc    Remove RPMs
 
-     --label           Set one or more build labels. The build looks for a 
+     --label|-l        Set one or more build labels. The build looks for a 
                        meta/{label}.configure-switches file in each project
                        and uses these switches if the file is found.
                        Multiple labels may be specified by multiple uses of this
