[XPB-337] [XCS-44] Improved utility for generating SSL keys and certificates
See sipXcommserverLib/doc/INSTALL.ssl

http://track.sipfoundry.org/browse/XPB-337
http://track.sipfoundry.org/browse/XCS-44



git-svn-id: http://scm.sipfoundry.org/rep/sipX/main@5865 a612230a-c5fa-0310-af8b-88eea846685b

diff --git a/sipXcommserverLib/bin/ssl-cert/install-cert.sh.in b/sipXcommserverLib/bin/ssl-cert/install-cert.sh.in
--- a/sipXcommserverLib/bin/ssl-cert/install-cert.sh.in
+++ b/sipXcommserverLib/bin/ssl-cert/install-cert.sh.in
@@ -10,25 +10,11 @@
 ##
 
 Action=INSTALL
-InstallCA=TRUE
 Basename=""
 
 while [ $# -ne 0 ]
 do
     case ${1} in
-        ##
-        ## handle a flag with no value followiing
-        ##
-        -s|--server-only)
-            InstallCA=FALSE
-            ;;
-
-        ##
-        ## handle the 'end of options' marker
-        ##
-        --)
-            ;;
-
         ##
         ## handle an unknown switch
         ##
@@ -37,6 +23,7 @@ do
             break
             ;;
 
+        # positional arguments
         *)
             if [ -z "${Basename}" ]
             then
@@ -52,62 +39,127 @@ do
     shift # always consume 1
 done
 
+if [ -z "${Basename}" ]
+then
+    Basename=`hostname --fqdn`
+fi
 
-if [ "${Action}" = "USAGE" -o -z "${Basename}" ]
+if ! [ -f "${Basename}.crt" -a -f "${Basename}.key" ]
+then
+    cat <<EOF 1>&2
+! Certificate and key not found for ${Basename}
+  ${Basename}.crt
+  ${Basename}.key
+
+EOF
+    Action=USAGE
+fi
+
+if [ "${Action}" = "USAGE" ]
 then
     cat <<EOF
 Usage:
-   install-cert.sh [--server-only] <file-base>
+   install-cert.sh [ <server-name> ]
 
-   The file-base specifies the base name of the .key and .crt files
-   generated by the self-certify script.
+   The server-name specifies the base name of the .key and .crt files
+   generated by the gen-ssl-keys.sh script.  If not specified, it defaults
+   to the fully qualified host name of the system.
+
+   The certificate is examined to find the issuer name; if a CA certificate
+   is found in the same directory with that name (with a '.crt' suffix),
+   than that certificate is installed as a trusted authority.
 
 EOF
     exit 1
 fi
 
-if [ $InstallCA = TRUE ]
-then
+caName=`@OPENSSL@ x509 -in "${Basename}.crt" -issuer -nameopt RFC2253,multiline -noout | perl -ne 'use English; m/^ +commonName += / && print $POSTMATCH'`
 
-    # create the sipX authorities store directory
-    if [ ! -d @SIPX_CONFDIR@/ssl/authorities ]
+if [ -n "${caName}" -a -f "${caName}.crt" ]
     then
-        mkdir               @SIPX_CONFDIR@/ssl/authorities || exit 1
-        chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl/authorities || exit 1
-        chmod 0700          @SIPX_CONFDIR@/ssl/authorities || exit 1
-    fi
-      
-    # install the ca certificate as a trusted ca
-    cp    ca.crt        @SIPX_CONFDIR@/ssl/authorities/ca.crt || exit 1
-    chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl/authorities/ca.crt || exit 1
-    chmod 0644          @SIPX_CONFDIR@/ssl/authorities/ca.crt || exit 1
-
-    # regenerate the hash symlinks for the certificate store
-    @bindir@/ssl-cert/ca_rehash 
-
+    AuthoritySwitch="--authority ${caName}.crt"
+else
+    AuthoritySwitch=""
 fi
 
-@bindir@/ssl-cert/check-cert.sh --verbose $Basename.crt 
+echo "Checking the ${Basename} certificate"
 
-if [ ! -d @SIPX_CONFDIR@/ssl ]
+if @bindir@/ssl-cert/check-cert.sh ${AuthoritySwitch} $Basename.crt 
 then
-    mkdir               @SIPX_CONFDIR@/ssl || exit 1
-    chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl || exit 1
-    chmod 0700          @SIPX_CONFDIR@/ssl || exit 1
-fi
 
-# install the certificate
-cp    $Basename.crt @SIPX_CONFDIR@/ssl/ssl.crt || exit 1
-chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl/ssl.crt || exit 1
-chmod 0600          @SIPX_CONFDIR@/ssl/ssl.crt || exit 1
+    if [ ! -d @SIPX_CONFDIR@/ssl ]
+    then
+        mkdir               @SIPX_CONFDIR@/ssl || exit 1
+        chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl || exit 1
+        chmod 0700          @SIPX_CONFDIR@/ssl || exit 1
+    fi
 
-# install the private key
-cp    $Basename.key @SIPX_CONFDIR@/ssl/ssl.key || exit 1
-chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl/ssl.key || exit 1
-chmod 0600          @SIPX_CONFDIR@/ssl/ssl.key || exit 1
+    if [ -n "${caName}" -a -f "${caName}.crt" ]
+    then
+        # create the sipX authorities store directory
+        if [ ! -d @SIPX_CONFDIR@/ssl/authorities ]
+        then
+            mkdir               @SIPX_CONFDIR@/ssl/authorities || exit 1
+            chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl/authorities || exit 1
+            chmod 0700          @SIPX_CONFDIR@/ssl/authorities || exit 1
+        fi
+        
+        echo "Installing ${caName}.crt certificate as a trusted CA"
+        cp -v ${caName}.crt @SIPX_CONFDIR@/ssl/authorities/${caName}.crt || exit 1
+        chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl/authorities/${caName}.crt || exit 1
+        chmod 0644          @SIPX_CONFDIR@/ssl/authorities/${caName}.crt || exit 1
 
-cat <<EOF
+        # regenerate the hash symlinks for the certificate store
+        @bindir@/ssl-cert/ca_rehash 
+    fi
+
+    echo "Installing the ${Basename} certificate"
+    cp -v $Basename.crt @SIPX_CONFDIR@/ssl/ssl.crt || exit 1
+    chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl/ssl.crt || exit 1
+    chmod 0600          @SIPX_CONFDIR@/ssl/ssl.crt || exit 1
+
+    echo "Installing the ${Basename} private key"
+    cp -v $Basename.key @SIPX_CONFDIR@/ssl/ssl.key || exit 1
+    chown @SIPXPBXUSER@ @SIPX_CONFDIR@/ssl/ssl.key || exit 1
+    chmod 0600          @SIPX_CONFDIR@/ssl/ssl.key || exit 1
+
+    echo "Checking the installed certificate"
+    if @bindir@/ssl-cert/check-cert.sh @SIPX_CONFDIR@/ssl/ssl.crt
+    then
+        cat <<EOF
 
   Your sipX SSL security is now configured.
 
 EOF
+
+    cert_expires=`@OPENSSL@ x509 -in "${Basename}.crt" -noout -enddate | sed 's/notAfter=//'`
+
+    cat <<EOF
+
+  Your server certificate will expire ${cert_expires}. 
+
+EOF
+
+    else
+        echo "Post-install check failed." 1>&2
+        exit 1;
+    fi
+
+else
+    cat <<EOF 1>&2
+
+! Check failed - certificate and key not installed.
+EOF
+
+    if [ -n "${caName}" ]
+    then
+        cat <<EOF 1>&2
+
+  You may need to obtain the root certificate for your CA (${caName}).
+  If you get a copy of the root certificate, put it in this directory, named
+  ${caName}.crt and rerun this command.
+
+EOF
+    fi
+    exit 1;
+fi
