Fix a bug where sipxconfig.sh was exiting because of a bad database version, even when the user was trying to drop/create the database to fix the problem.  Now we only check the database version in configtest and when running the web UI, and not when the user is doing just a database command.
git-svn-id: http://scm.sipfoundry.org/rep/sipX/main@5293 a612230a-c5fa-0310-af8b-88eea846685b

diff --git a/sipXconfig/web/bin/sipxconfig.sh.in b/sipXconfig/web/bin/sipxconfig.sh.in
--- a/sipXconfig/web/bin/sipxconfig.sh.in
+++ b/sipXconfig/web/bin/sipxconfig.sh.in
@@ -21,7 +21,6 @@ Args=""
 : ${ConfigFiles:=@sipxpbx.conf.dir@/sipxconfig.properties @sipxpbx.conf.dir@/topology.xml}
 : ${PidFile:=@sipxpbx.run.dir@/sipxconfig.pid}
 : ${DatabaseProject:=@sipxpbx.conf.dir@/database/database.xml}
-: ${DatabaseVersion:=1}
 : ${LibDir:=@sipxconfig.lib.dir@}
 : ${Psql:=psql}
 : ${ServiceDir:=/etc/init.d}
@@ -140,6 +139,7 @@ onWebUi() {
     runConfigpp
 
     databaseCommand upgrade
+    databaseVersionCheck
 
     makeRestoreBackup @sipxpbx.conf.dir@/config.defs
     makeRestoreBackup @sipxpbx.conf.dir@/proxy-config.in
@@ -177,26 +177,33 @@ onWebUi() {
 #  1. not running 
 #  2. running but not setup to communicate w/java or ${Psql} command
 #  3. Database is not created
-#
-# Check the database version.  If it is wrong, then exit, because it's dangerous to
-# run sipXconfig on top of the wrong database version.
 databaseCheck() {
     if ! ${Psql} -l -U postgres | grep "${Database}" >/dev/null
     then        
         return 1
     else
-        dbver=`${Psql} -c "select vh.version from version_history vh;" ${Database} postgres | sed -n 's/^\s*\([0-9][0-9]*\)\s*$/\1/p'`
-        if [ "$dbver" != $RequiredDatabaseVersion ]
-        then
-            if [ "$dbver" == 0 ]
-            then
-                echo "Error: bad database version.  This database was created by a prerelease version of sipXconfig.  You should drop and recreate the database via \"sipxconfig.sh --database drop create\".  Exiting now."
-            else
-                echo "Error: bad database version.  Expected version $RequiredDatabaseVersion, got version $dbver.  This database was created or modified by a newer version of sipXconfig.  Exiting now."
-            fi
-            exit 1
-        fi
         return 0
+    fi
+}
+
+# Check the database version.  If it is wrong, then exit, because it's dangerous to
+# run sipXconfig on top of the wrong database version.
+databaseVersionCheck() {
+    dbver=`${Psql} -c "select vh.version from version_history vh;" ${Database} postgres | sed -n 's/^\s*\([0-9][0-9]*\)\s*$/\1/p'`
+    if [ "$dbver" = "" ]
+    then
+	echo "Error: could not get the database version.  Exiting now."
+	exit 1
+    fi
+    if [ "$dbver" != $RequiredDatabaseVersion ]
+    then
+        if [ "$dbver" == 0 ]
+        then
+            echo "Error: bad ${Database} database version.  This database was created by a prerelease version of sipXconfig.  You should drop and recreate the database via \"sipxconfig.sh --database drop create\".  Exiting now."
+        else
+            echo "Error: bad ${Database} database version.  Expected version $RequiredDatabaseVersion, got version $dbver.  This database was created or modified by a newer version of sipXconfig.  Exiting now."
+        fi
+        exit 1
     fi
 }
 
@@ -298,7 +305,7 @@ setPostgresRunlevels() {
 configtest() {
     @bin.dir@/sipx-validate-xml @sipxpbx.conf.dir@/topology.xml.in
     Status=$(($Status+$?))
-    databaseCheck
+    databaseVersionCheck
     Status=$(($Status+$?))
 
     # Print out a success message if everything is OK, to give the user some feedback.
