mergefrom sipx 7522-7559
Update from sipX Main.


git-svn-id: http://scm.sipfoundry.org/rep/sipX/branches/user_dworley_redirectors@7561 a612230a-c5fa-0310-af8b-88eea846685b

diff --git a/sipXconfig/web/bin/sipxconfig.sh.in b/sipXconfig/web/bin/sipxconfig.sh.in
--- a/sipXconfig/web/bin/sipxconfig.sh.in
+++ b/sipXconfig/web/bin/sipxconfig.sh.in
@@ -121,7 +121,6 @@ databaseCommand() {
         @sipxpbx.conf.dir@ \
         ${LibDir}/*.jar`
 
-    echo "*** Optional check for tools.jar, OK if not found..."
     $JavaCmd \
         -Djava.net.preferIPv4Stack=true \
         -classpath $Classpath \
@@ -132,7 +131,8 @@ databaseCommand() {
         -Dlog.dir=${LogDir} \
         -Dtmp.dir=${TmpDir} \
         -f ${DatabaseProject} \
-        $@
+        $@ \
+        > /dev/null 2>&1
 }
 
 runningUserCheck() {
@@ -194,43 +194,57 @@ onWebUi() {
 #  2. running but not setup to communicate w/java or ${Psql} command
 #  3. Database is not created
 databaseCheck() {
-    if ! ${Psql} -l -U postgres | grep "${Database}" >/dev/null
-    then        
-        return 1
-    else
-        return 0
-    fi
+    ${Psql} --list --field-separator , --no-align --username postgres \
+    | cut --delimiter , --fields 1 \
+    | grep "${Database}" > /dev/null 2>&1
 }
 
 # Check the database version.  If it is wrong, then exit, because it's dangerous to
 # run sipXconfig on top of the wrong database version.
 databaseVersionCheck() {
-    dbver=`${Psql} -c "select max(vh.version) from version_history vh;" ${Database} postgres | sed -n 's/^\s*\([0-9][0-9]*\)\s*$/\1/p'`
-    if [ "$dbver" = "" ]
+    dbver=`${Psql} --tuples-only --no-align \
+           --command "select max(vh.version) from version_history vh;" \
+           ${Database} postgres`
+    if [ $? -ne 0 -o "$dbver" = "" ]
     then
-	echo "Error: could not get the database version.  Exiting now."
-	exit 1
+        echo "Error: could not get the database version.  Exiting now."
+        exit 1
     fi
-    if [ "$dbver" != $RequiredDatabaseVersion ]
+    if [ "$dbver" -ne $RequiredDatabaseVersion ]
     then
-        if [ "$dbver" == 0 ]
+        if [ $dbver -eq 0 ]
         then
-            echo "Error: bad ${Database} database version.  This database was created by a prerelease version of sipXconfig.  You should drop and recreate the database via \"sipxconfig.sh --database drop create\".  Exiting now."
+            cat <<EOF 
+    Error: bad ${Database} database version.  
+    This database was created by a prerelease version of sipXconfig.  
+    You should drop and recreate the database by running:
+
+        @bin.dir@/sipxconfig.sh --database drop create
+
+    Exiting now."
+EOF
         else
-            echo "Error: bad ${Database} database version.  Expected version $RequiredDatabaseVersion, got version $dbver.  This database was created or modified by a newer version of sipXconfig.  Exiting now."
+            cat <<EOF
+    Error: bad ${Database} database version.
+    Expected version $RequiredDatabaseVersion, got version $dbver.  
+    This database was created or modified by a newer version of sipXconfig.  
+    Exiting now."
+EOF
         fi
         exit 1
     fi
 }
 
-# Called after installation or upgrade by distro's package infrastructure
+# Called as root in sipxpbx startup script to do initial setup,
 # but can be called manually and is harmless if called multiple times.
 onSetup() {
    if ! databaseCheck
    then
+       echo "Initializing configuration database..."
        postgresSetup
        setPostgresRunlevels
        databaseCommand create
+       echo -n "Configuration database initialized"
    fi
 }
 
@@ -321,7 +335,14 @@ setPostgresRunlevels() {
 
 # simple diagnostics
 configtest() {
-    if ! databaseCheck; then
+    if ! databaseCheck
+    then
+      cat <<EOF
+    Postgres configuration database not detected.
+    Run (as root:)
+
+       @bin.dir@/sipxconfig.sh --setup
+EOF
       Status=1
     fi
     @bin.dir@/sipx-validate-xml @sipxpbx.conf.dir@/topology.xml.in
@@ -331,7 +352,7 @@ configtest() {
     # If there is an error then the test will yield an error message.
     if [ $Status = 0 ]
     then
-	echo "The config test succeeded."
+        echo "The config test succeeded."
     fi
 }
 
