- changes to upgrade to log4j 1.2.9 - sipXconfig was using quite old log4j: it was incompatible with the one used by current JBoss - postgres JDBC library turned out to be incompatible as well - it is upgraded to lib/pg74.215.jdbc3.jar - many small changes to build files - to reference new J2EE libraries - they are now in different directories than in old JBoss - modifications to component managed persistence - while we stay with CMP 1.x for now, JBoss 4.x does not offer jaws (O/R mapper) any more, we need to support jbosscmp-jdbc mechanism, this is responsible for several changes (mostly in finder definitions) in ejb-jar.xml - all XML descriptor files use current DTDs distributed with JBoss - that should allow for running sipXconfig even without connection to DTDs published on the WEB - login mechanism changes - custom login module SIPxchange LoginModule has been upgraded - custom optimizations to EJB configurations in jboss.xml were largely JBoss 2.4 specific - they were temporarily removed - minor exception handling changes - in many places sipXconfig code was catching (and ignoring or repackaging with information loss) all exceptions including runtime exceptions - this made quite impossible to diagnose problems related to upgrade; in several places code was rewritten to catch only checked exceptions - minor EJB related problems - classes lacking default constructors or not enabled for marshaling (serializing) - custom tags that reference unused classes had to be removed - there is a new JNDI binding for QueueConnectionFactory - it's now called ConnectionFactory - upgrades to progfilegenerator.sh(.in) start up script - to run the latest JBoss 4.x - a new environment variable you can set JBOSS_SERVER_CONF if you want to run several separate configurations without installing separate copies of JBoss
git-svn-id: http://scm.sipfoundry.org/rep/sipX/old/sipXconfig/main@3255 a612230a-c5fa-0310-af8b-88eea846685b

diff --git a/profilegenerator/deploy/bin/profilegenerator.sh.in b/profilegenerator/deploy/bin/profilegenerator.sh.in
--- a/profilegenerator/deploy/bin/profilegenerator.sh.in
+++ b/profilegenerator/deploy/bin/profilegenerator.sh.in
@@ -26,21 +26,81 @@ fi
 # Needed for Jasper page compiler (possibly for other components as well)
 export JAVA_HOME=`@bin.dir@/sipx-config --jdk`
 
-# Needed for @jboss.home@/bin/run.sh
-export PATH=${JAVA_HOME}/bin:$PATH
-
 echo $$ > @sipxpbx.run.dir@/profilegenerator.pid
 
+if [ "x${JBOSS_HOME}" = "x" ]; then
+	JBOSS_HOME=@jboss.home@
+fi
+
 # Production command line
-cd @jboss.home@/bin
+cd ${JBOSS_HOME}/bin
 
 # portions extracted from jboss's run.sh, stopped trying to 
 # run jboss's startup script because too hard to kill by
 # pid
-export JBOSS_CLASSPATH=${JAVA_HOME}/lib/tools.jar:run.jar:../lib/crimson.jar
-# assume modern jdk
-HOTSPOT="-server"
-JAXP=-Djavax.xml.parsers.DocumentBuilderFactory=org.apache.crimson.jaxp.DocumentBuilderFactoryImpl
-JAXP="$JAXP -Djavax.xml.parsers.SAXParserFactory=org.apache.crimson.jaxp.SAXParserFactoryImpl"
 
-exec java $HOTSPOT -mx256m $PROFILEGENERATOR_OPTS $JAXP -classpath $JBOSS_CLASSPATH org.jboss.Main catalina $@
+DIRNAME=`dirname $0`
+PROGNAME=`basename $0`
+
+#
+# Helper to complain.
+#
+warn() {
+    echo "${PROGNAME}: $*"
+}
+
+# Use the maximum available, or set MAX_FD != -1 to use that
+MAX_FD="maximum"
+
+# Increase the maximum file descriptors if we can
+MAX_FD_LIMIT=`ulimit -H -n`
+if [ $? -eq 0 ]; then
+if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
+    # use the system max
+    MAX_FD="$MAX_FD_LIMIT"
+fi
+
+ulimit -n $MAX_FD
+if [ $? -ne 0 ]; then
+    warn "Could not set maximum file descriptor limit: $MAX_FD"
+fi
+else
+	warn "Could not query system maximum file descriptor limit: $MAX_FD_LIMIT"
+fi
+
+# Setup the JVM
+if [ "x$JAVA" = "x" ]; then
+	JAVA="$JAVA_HOME/bin/java"
+fi
+
+# Setup the classpath
+runjar="$JBOSS_HOME/bin/run.jar"
+if [ ! -f $runjar ]; then
+    warn "Missing required file: $runjar"
+    exit 1
+fi
+JBOSS_BOOT_CLASSPATH="$runjar"
+
+# Include the JDK javac compiler for JSP pages. The default is for a Sun JDK
+# compatible distribution which JAVA_HOME points to
+if [ "x$JAVAC_JAR" = "x" ]; then
+    JAVAC_JAR="$JAVA_HOME/lib/tools.jar"
+fi
+
+if [ "x$JBOSS_CLASSPATH" = "x" ]; then
+    JBOSS_CLASSPATH="$JBOSS_BOOT_CLASSPATH:$JAVAC_JAR"
+else
+    JBOSS_CLASSPATH="$JBOSS_CLASSPATH:$JBOSS_BOOT_CLASSPATH:$JAVAC_JAR"
+fi
+
+# append profilegenerator opts
+JAVA_OPTS="-server $JAVA_OPTS $PROFILEGENERATOR_OPTS"
+
+# Setup the java endorsed dirs
+JBOSS_ENDORSED_DIRS="$JBOSS_HOME/lib/endorsed"
+
+exec "$JAVA" $JAVA_OPTS \
+	-Dprogram.name="$PROGNAME" \
+	-Djava.endorsed.dirs="$JBOSS_ENDORSED_DIRS" \
+      -classpath "$JBOSS_CLASSPATH" \
+      org.jboss.Main -c @jboss.server.conf@
