Fix XCF-393: Update database version number to match before release
git-svn-id: http://scm.sipfoundry.org/rep/sipX/main/sipXconfig@5282 a612230a-c5fa-0310-af8b-88eea846685b

diff --git a/web/bin/sipxconfig.sh.in b/web/bin/sipxconfig.sh.in
--- a/web/bin/sipxconfig.sh.in
+++ b/web/bin/sipxconfig.sh.in
@@ -11,7 +11,7 @@ Action=RUN
 Status=0
 Args=""
 
-# Declare script variables in a manner that unittest
+# Declare script variables in a manner that unit test
 # (or end user I suppose) can override
 : ${SslDir:=@sipxpbx.conf.dir@/ssl}
 : ${AuthoritiesDir:=$SslDir/authorities}
@@ -21,6 +21,7 @@ Args=""
 : ${ConfigFiles:=@sipxpbx.conf.dir@/sipxconfig.properties @sipxpbx.conf.dir@/topology.xml}
 : ${PidFile:=@sipxpbx.run.dir@/sipxconfig.pid}
 : ${DatabaseProject:=@sipxpbx.conf.dir@/database/database.xml}
+: ${DatabaseVersion:=1}
 : ${LibDir:=@sipxconfig.lib.dir@}
 : ${Psql:=psql}
 : ${ServiceDir:=/etc/init.d}
@@ -30,6 +31,7 @@ Args=""
 : ${TmpDir:=@sipxpbx.tmp.dir@}
 
 Database=SIPXCONFIG
+RequiredDatabaseVersion=1
 
 # This function determines the correct service name for Postgres.
 postgresService() {
@@ -96,8 +98,8 @@ createAuthoritiesTruststore() {
 }
 
     
-# Take a list of files for directories complete with 
-# and expand pathnames to create string for PATH based variables 
+# Take a list of files or directories 
+# and expand pathnames to create a string for PATH-based variables 
 classpath() {
     Cpath=""
     for f in $@; do
@@ -171,21 +173,35 @@ onWebUi() {
 	    org.mortbay.jetty.Server @sipxpbx.conf.dir@/sipxconfig-jetty.xml
 }
 
-# return false if postgres is 
+# Return false if postgres is 
 #  1. not running 
 #  2. running but not setup to communicate w/java or ${Psql} command
 #  3. Database is not created
+#
+# Check the database version.  If it is wrong, then exit, because it's dangerous to
+# run sipXconfig on top of the wrong database version.
 databaseCheck() {
     if ! ${Psql} -l -U postgres | grep "${Database}" >/dev/null
     then        
         return 1
     else
+        dbver=`${Psql} -c "select vh.version from version_history vh;" ${Database} postgres | sed -n 's/^\s*\([0-9]\)\s*$/\1/p'`
+        if [ "$dbver" != $RequiredDatabaseVersion ]
+        then
+            if [ "$dbver" == 0 ]
+            then
+                echo "Error: bad database version.  This database was created by a prerelease version of sipXconfig.  You should drop and recreate the database via \"sipxconfig.sh --database drop create\".  Exiting now."
+            else
+                echo "Error: bad database version.  Expected version $RequiredDatabaseVersion, got version $dbver.  This database was created or modified by a newer version of sipXconfig.  Exiting now."
+            fi
+            exit 1
+        fi
         return 0
     fi
 }
 
 # Called after installation or upgrade by distro's package infrastructure
-# but can be called manually and is harmless if called mulitple times.
+# but can be called manually and is harmless if called multiple times.
 onSetup() {
    if ! databaseCheck
    then
@@ -223,14 +239,14 @@ postgresSetup() {
       $SubstituteUser - postgres -c "initdb --pgdata=$PGDATA"
   fi
 
-  # Create back up file (possibly) requiring update
+  # Create backup file (possibly) requiring update
   if [ ! -f $PGDATA/pg_hba.conf-sipx.bak ]
   then
      cp $PGDATA/pg_hba.conf $PGDATA/pg_hba.conf.sipx.bak
   fi
 
-  # Will allow this script to add user. Need to be listed before
-  # other permission or it will not take affect
+  # Will allow this script to add user.  Needs to be listed before
+  # other permission or it will not take effect.
   if ! grep '^local *all *all *trust\b*$' $PGDATA/pg_hba.conf >/dev/null
   then
      echo "local all all trust" > $PGDATA/pg_hba.conf.tmp
@@ -238,8 +254,8 @@ postgresSetup() {
      mv $PGDATA/pg_hba.conf.tmp $PGDATA/pg_hba.conf
   fi
 
-  # Will allow jboss to connect. Need to be listed before
-  # other permission or it will not take affect
+  # Will allow jdbc to connect.  Needs to be listed before
+  # other permission or it will not take effect.
   if ! grep '^host *all *all *127.0.0.1 *255.255.255.255 *trust\b*$' $PGDATA/pg_hba.conf >/dev/null
   then
      echo "host all all 127.0.0.1 255.255.255.255 trust" > $PGDATA/pg_hba.conf.tmp
@@ -247,7 +263,7 @@ postgresSetup() {
      mv $PGDATA/pg_hba.conf.tmp $PGDATA/pg_hba.conf
   fi
 
-  # Open up tcpid connections
+  # Open up TCP/IP connections
   sed -i-sipx.bak -e 's/\#tcpip_socket\s=\sfalse/tcpip_socket = true/g' \
           $PGDATA/postgresql.conf
   ${Chown} postgres:postgres $PGDATA/postgresql.conf
@@ -280,9 +296,10 @@ setPostgresRunlevels() {
 
 # simple diagnostics
 configtest() {
-    # comment out until (benign?) xml errors are resolved
     @bin.dir@/sipx-validate-xml @sipxpbx.conf.dir@/topology.xml.in
     Status=$(($Status+$?))
+    databaseCheck
+    Status=$(($Status+$?))    
 }
 
 while [ $# -ne 0 ]
@@ -337,8 +354,8 @@ Usage: sipxconfig.sh [-d|--database commands ...]
                      [-s|--setup]
                      [-h|--help]
                      
-Start Web UI administration for sipXpbx and for remotely provision
-SIP based phones.
+Start Web UI administration for sipXpbx and for remotely provisioned
+SIP-based phones.
 
 Options include:
 
@@ -369,7 +386,7 @@ Notable environment variables:
 
     POSTGRES_SERVICE   a guess is made to determine the name for the
                        Postgres service.
-                       If the guess incorrect, set this to the name of
+                       If the guess is incorrect, then set this to the name of
                        the script in /etc/init.d that starts/stops
                        the Postgres database.  The possibilities that
                        we are aware of are "postgresql" and "rhdb".
