[XPB-1014] fix parsing of --logs option with explicit output file name
git-svn-id: http://scm.sipfoundry.org/rep/sipX/main@9252 a612230a-c5fa-0310-af8b-88eea846685b

diff --git a/sipXpbx/bin/sipx-snapshot.in b/sipXpbx/bin/sipx-snapshot.in
--- a/sipXpbx/bin/sipx-snapshot.in
+++ b/sipXpbx/bin/sipx-snapshot.in
@@ -61,17 +61,25 @@ do
             ;;
 
         -l|--logs)
-            Logs=`echo ${2} | tr A-Z a-z`
-            case ${Logs} in
-                current|none|all)
-                    :
-                    ;;
-                *)
-                    echo "invalid selector for ${1}: '${2}'" 1>&2
-                    Action=USAGE
-                    break
-                    ;;
-            esac
+            if [ -z "${2}" ]
+            then
+                echo "No argument supplied for ${1}" 1>&2
+                Action=USAGE
+                break
+            else
+                Logs=`echo ${2} | tr A-Z a-z`
+                case ${Logs} in
+                    current|none|all)
+                        :
+                        ;;
+                    *)
+                        echo "invalid selector for ${1}: '${2}'" 1>&2
+                        Action=USAGE
+                        break
+                        ;;
+                esac
+            fi
+            shift
             ;;
 
         -nl|--no-logs)
