first cut at adding sipXrepro project
git-svn-id: http://scm.sipfoundry.org/rep/sipX/branches/repro-proxy@6161 a612230a-c5fa-0310-af8b-88eea846685b

diff --git a/sipXpbx/bin/sipxpbx.in b/sipXpbx/bin/sipxpbx.in
--- a/sipXpbx/bin/sipxpbx.in
+++ b/sipXpbx/bin/sipxpbx.in
@@ -70,14 +70,13 @@ ulimit -c ${SIPX_CORELIMIT:-0}
 # the ProcessDefinitions.xml and Watchdog.xml
 sipxchange_processes=(
     watchdog
-    sipproxy
     sipxconfig
     sipXvxml
     sipxpark
     sipxpresence
     sipstatus
     sipregistrar
-    sipauthproxy
+    sipxrepro
     keepalive
 )
 
@@ -210,28 +209,31 @@ configtest() { # process-name  process-wd  process-command
     unset BASH_ENV
     
     status=0
-    if [ $iam = @SIPXPBXUSER@ ]
+    if [ -x $proc_cmd ]
     then
-        if [ -x $proc_cmd ]
+        if [ $iam = @SIPXPBXUSER@ ]
         then
-            $proc_cmd --configtest
-            status=$?
+                $proc_cmd --configtest
+                status=$?
+        elif [ $iam = root ]
+        then
+            su @SIPXPBXUSER@ -c \
+              "test -x $proc_cmd && $proc_cmd --configtest; echo \$? > @SIPX_RUNDIR@/$proc_name.result"
+            status=`cat @SIPX_RUNDIR@/$proc_name.result`
+            rm -f @SIPX_RUNDIR@/$proc_name.result
         else
-            echo "configtest: tbd: not found '$proc_cmd'"
+            echo "You must be able to run as @SIPXPBXUSER@" 1>&2
+            exit 1
         fi
-    elif [ $iam = root ]
-    then
-        su @SIPXPBXUSER@ -c \
-          "test -x $proc_cmd && $proc_cmd --configtest; echo \$? > @SIPX_RUNDIR@/$proc_name.result"
-        status=`cat @SIPX_RUNDIR@/$proc_name.result`
-        rm -f @SIPX_RUNDIR@/$proc_name.result
     else
-        echo "You must be able to run as @SIPXPBXUSER@" 1>&2
-        exit 1
+        echo "Installation error? '$proc_cmd' not found" 1>&2
+        status=1
     fi
 
-    test $status -eq 0 && echo "    OK"
-    return $status
+    test "$status" = 0 && echo "    OK"
+    # This assures that our return is either 0 or 1, regardless of what
+    # $status was.
+    return $?
 }
 
 
@@ -461,15 +463,15 @@ do_start() {
         start watchdog 
 
         # Wait for keepalive to prime the IMDB, as the CGIs need them
-        echo -n " Waiting for keepalive to start: "
+        echo -n " Waiting for keepalive"
         for seconds in `seq 20 -1 0`
         do
             test -e @SIPX_RUNDIR@/keepalive.pid && break
             [ $seconds == 0 ] && break
-            echo -n "$seconds "
+            echo -n "."
             sleep 1
         done
-        [ $seconds == 0 ] && echo_failure || echo_success
+        test -e @SIPX_RUNDIR@/keepalive.pid && echo_success || echo_failure
         echo
         
         sleep 1
