XPB-562, XPB-563: Add configuration script for the HA distributed machine(s).
git-svn-id: http://scm.sipfoundry.org/rep/sipX/main@6645 a612230a-c5fa-0310-af8b-88eea846685b

diff --git a/sipXproxy/bin/sipxcallresolver.sh.in b/sipXproxy/bin/sipxcallresolver.sh.in
--- a/sipXproxy/bin/sipxcallresolver.sh.in
+++ b/sipXproxy/bin/sipxcallresolver.sh.in
@@ -321,69 +321,72 @@ configCheck() {
       echo "  authproxy configured for logging"
    fi
    
-   resolveOk=1
-   resolveConfig=`cat @SIPX_CONFDIR@/callresolver-config.in | grep SIP_CALLRESOLVER_DAILY_RUN`
-   if ! expr match "$resolveConfig" '.*:\s*[eE][nN][aA][bB][lL][eE]\s*$' >/dev/null; then
-      echo
-      echo "  Warning: call resolver is not configured for daily runs. This"
-      echo "           will prevent the call resolver from automatically"
-      echo "           resolving calls and purging old database records"
-      echo "           on a regular basis. Add the line"
-      echo              
-      echo "              SIP_CALLRESOLVER_DAILY_RUN : ENABLE"
-      echo
-      echo "           to @SIPX_CONFDIR@/callresolver-config.in"
-      echo 
-      resolveOk=0
-      Status=0
-   fi
-
-   resolveConfig=`cat @SIPX_CONFDIR@/callresolver-config.in | grep SIP_CALLRESOLVER_PURGE`
-   if ! expr match "$resolveConfig" '.*:\s*[eE][nN][aA][bB][lL][eE]\s*$' >/dev/null; then
-      echo
-      echo "  Warning: call resolver is not configured for purging old records."
-      echo "           This will prevent the call resolver from automatically"
-      echo "           purging old database records on a regular basis. Add"
-      echo "           the line"
-      echo              
-      echo "              SIP_CALLRESOLVER_PURGE  : ENABLE"
-      echo
-      echo "           to @SIPX_CONFDIR@/callresolver-config.in"
-      echo
-      resolveOk=0
-      Status=0
-   fi
-   
-   if [ $resolveOk = 1 ]; then
-      echo "  call resolver configuration ok"
-   fi   
-   
-   echo -n "Checking for @SIPX_SYSCONFDIR@/cron.daily/callresolver_run..."
-   if [ -f @SIPX_SYSCONFDIR@/cron.daily/callresolver_run ]; then
-      if [ -x @SIPX_SYSCONFDIR@/cron.daily/callresolver_run ]; then
-         echo " ok"
-      else  
+   # Don't check configuration of call resolver for distributed machines
+   if [ ${Action} = CONFIGTEST ]; then
+      resolveOk=1
+      resolveConfig=`cat @SIPX_CONFDIR@/callresolver-config.in | grep SIP_CALLRESOLVER_DAILY_RUN`
+      if ! expr match "$resolveConfig" '.*:\s*[eE][nN][aA][bB][lL][eE]\s*$' >/dev/null; then
          echo
-         echo "  Error: File found but not executable"
+         echo "  Warning: call resolver is not configured for daily runs. This"
+         echo "           will prevent the call resolver from automatically"
+         echo "           resolving calls and purging old database records"
+         echo "           on a regular basis. Add the line"
+         echo              
+         echo "              SIP_CALLRESOLVER_DAILY_RUN : ENABLE"
+         echo
+         echo "           to @SIPX_CONFDIR@/callresolver-config.in"
+         echo 
+         resolveOk=0
+         Status=0
+      fi
+
+      resolveConfig=`cat @SIPX_CONFDIR@/callresolver-config.in | grep SIP_CALLRESOLVER_PURGE`
+      if ! expr match "$resolveConfig" '.*:\s*[eE][nN][aA][bB][lL][eE]\s*$' >/dev/null; then
+         echo
+         echo "  Warning: call resolver is not configured for purging old records."
+         echo "           This will prevent the call resolver from automatically"
+         echo "           purging old database records on a regular basis. Add"
+         echo "           the line"
+         echo              
+         echo "              SIP_CALLRESOLVER_PURGE  : ENABLE"
+         echo
+         echo "           to @SIPX_CONFDIR@/callresolver-config.in"
+         echo
+         resolveOk=0
+         Status=0
+      fi
+   
+      if [ $resolveOk = 1 ]; then
+         echo "  call resolver configuration ok"
+      fi   
+   
+      echo -n "Checking for @SIPX_SYSCONFDIR@/cron.daily/callresolver_run..."
+      if [ -f @SIPX_SYSCONFDIR@/cron.daily/callresolver_run ]; then
+         if [ -x @SIPX_SYSCONFDIR@/cron.daily/callresolver_run ]; then
+            echo " ok"
+         else  
+            echo
+            echo "  Error: File found but not executable"
+            echo
+            Status=0
+         fi
+      else
+         echo
+         echo "  Error: @SIPX_SYSCONFDIR@/etc/cron.daily/callresolver_run not found."
          echo
          Status=0
       fi
-   else
-      echo
-      echo "  Error: @SIPX_SYSCONFDIR@/etc/cron.daily/callresolver_run not found."
-      echo
-      Status=0
-   fi
    
-   echo -n "Checking for @GEM_LIB_DIR@/sipxcallresolver-1.0.0/main.rb..."
-   if [ -f @GEM_LIB_DIR@/sipxcallresolver-1.0.0/main.rb ]; then
-      echo " ok"
-   else
-      echo
-      echo "  Error: @GEM_LIB_DIR@/sipxcallresolver-1.0.0/main.rb not found."
-      echo
-      Status=0
-   fi   
+      echo -n "Checking for @GEM_LIB_DIR@/sipxcallresolver-1.0.0/main.rb..."
+      if [ -f @GEM_LIB_DIR@/sipxcallresolver-1.0.0/main.rb ]; then
+         echo " ok"
+      else
+         echo
+         echo "  Error: @GEM_LIB_DIR@/sipxcallresolver-1.0.0/main.rb not found."
+         echo
+         Status=0
+      fi   
+   fi
 }
 
 # Check the database version.  If it is wrong, then exit, because it's dangerous to
@@ -496,6 +499,10 @@ do
         --patch)
             Action=PATCH
             ;;
+            
+        --distrib-configtest)
+            Action=DISTRIBTEST
+            ;;
 
         --nop)
             Action=NOP
@@ -524,6 +531,10 @@ do
 done
 
 if [ ${Action} = CONFIGTEST ]
+then
+    configtest
+    exit $Status
+elif [ ${Action} = DISTRIBTEST ]
 then
     configtest
     exit $Status
